#server.port= 8082
#spring.application.name= bookcliente
#spring.profiles.active= dev
#spring.jpa.hibernate.ddl-auto= validete
#spring.flyway.baseline-on-migrate= false
#spring.flyway.enabled= true
#spring.flyway.locations= classpath:/db/migration
#spring.flyway.schemas= public
#spring.flyway.default-schema= public
#eureka.client.service-url.defaultZone= http://localhost:8080/eureka
server:
  port: 8082
spring:
  application:
    name: bookcliente
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validete
  flyway:
    baseline-on-migrate: true
    enabled: true  
    locations: classpath:/db/migration
    schemas: public
    default-schema: public 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
